package com.vish.enterprise_rag.enums;

public enum UserActionType {
    UPLOAD_DOCUMENT,
    DELETE_DOCUMENT,
    VIEW_DOCUMENT,
    CREATE_USER,
    DELETE_USER,
    EDIT_USER,
    ORGANIZATION_CREATE,
    ORGANIZATION_EDIT,
    ORGANIZATION_DELETE,
    ASSIGN_PERMISSION,
    LOGIN,
    LOGOUT
}