spring:
  #profile
  config:
    activate:
      on-profile: dev

  # Database configuration
  datasource:
    read:
      url: jdbc:postgresql://localhost:5432/enterprise_rag
      username: enterprise_rag
      password: ${POSTGRES_PASSWORD:vishsqlpassword}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
    write:
      url: jdbc:postgresql://localhost:5432/enterprise_rag
      username: enterprise_rag
      password: ${POSTGRES_PASSWORD:vishsqlpassword}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
