spring:
  #profile
  config:
    activate:
      on-profile: dev

  # Database configuration
  datasource:
    read:
      url: jdbc:postgresql://localhost:5432/enterprise_rag
      username: enterprise_rag
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
    write:
      jdbc-url: jdbc:postgresql://localhost:5432/enterprise_rag
      username: enterprise_rag
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
