spring:
  #profile
  config:
    activate:
      on-profile: dev

  # Database configuration
  datasource:
    read:
      jdbcUrl:
      username:
      password:
      maxPoolSize:
    write:
      jdbcUrl:
      username:
      password:
      maxPoolSize: