#******* Application Configuration *********
server:
  servlet:
    context-path: /enterprise-rag
  port: 8800

spring:
  application:
    name: enterprise-rag
  profiles:
    active: dev
  # ***** Java 21/25 Virtual Threads *****
  threads:
    virtual:
      enabled: true
  # ***** Kafka Configuration *****
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  # ***** Jpa Configuration *****
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        query:
          plan_cache_max_size: 64
          plan_parameter_metadata_max_size: 32
          in_clause_parameter_padding: true
  session:
    store-type: none

app:
  storage:
    upload-dir: storage/uploads
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 hours
